### ISSUE TITLE
Cargo.toml parsing skips child sections

### ISSUE THREAD

**Issue by alerque** [meain/vim-package-info#35]
There are several places dependencies can show up in Cargo TOML files. This plugin catches only parent sections, but its possible to have child sections that are in a dot namespace (e.g. `dependencies.<package_name>`) and typically indented like this:

```toml
[dependencies]
subprocess = "0.2.6"

  [dependencies.config]
  version = "0.11.0"
  default-features = false
  features = [ "yaml" ]

[build-dependencies]
clap = "3.0.0-beta.2"

  [build-dependencies.vergen]
  version = "5.0.1"
  default-features = false
  features = [ "build", "git" ]
```

Note the two things this plugin picks up on and the two it does not:

![image](https://user-images.githubusercontent.com/173595/118245145-1897b400-b4a9-11eb-9599-ac27f8c9497c.png)
